name: C/C++ CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  ubuntu_16:
    name: Ubuntu 16
    runs-on: ubuntu-22.04
    container: ubuntu:16.04
    steps:
    - name: install git
      run: apt-get update && apt-get install -y software-properties-common && add-apt-repository ppa:git-core/ppa && apt-get update -y && apt-get install git -y
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install packages
      run: apt-get update && sudo apt-get install -y zlib1g-dev gcc libcurl4-openssl-dev valgrind make
    - name: build
      run:  make
    - name: test
      run: make test
    - name: test valgrind
      run: ./test/test.sh mem
  ubuntu_18:
    name: Ubuntu 18
    runs-on: ubuntu-22.04
    container: ubuntu:18.04
    steps:
    - name: install git
      run: apt-get update && apt-get install -y software-properties-common && add-apt-repository ppa:git-core/ppa && apt-get update -y && apt-get install git -y
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install packages
      run: apt-get update && sudo apt-get install -y zlib1g-dev gcc libcurl4-openssl-dev valgrind make
    - name: build
      run:  make
    - name: test
      run: make test
    - name: test valgrind
      run: ./test/test.sh mem
  ubuntu_20:
    name: Ubuntu 20
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y zlib1g-dev gcc libcurl4-openssl-dev valgrind
    - name: build
      run:  make
    - name: test
      run: make test
    - name: test valgrind
      run: ./test/test.sh mem
  ubuntu_22:
    name: Ubuntu 22
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y zlib1g-dev gcc libcurl4-openssl-dev valgrind
    - name: build
      run:  make
    - name: test
      run: make test
    - name: test valgrind
      run: ./test/test.sh mem
  # os_x:
  #   name: OSX
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       submodules: recursive
  #   - name: build
  #     run: make
  #   - name: test
  #     run: make test
  #   - name: test valgrind
  #     run: ./test/test.sh mem
