---
name: Release simulation

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  centos_7:
    name: centos_7
    runs-on: ubuntu-24.04
    container: centos:7
    steps:
    - name: install git
      run: sed -i -e '/^mirrorlist/d;/^#baseurl=/{s,^#,,;s,/mirror,/vault,;}' /etc/yum.repos.d/CentOS*.repo && yum update -y && yum install -y git
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install packages
      run: yum update -y && yum install -y install libcurl-devel zlib-devel gcc make wget
    - name: env
      run: ldd --version && gcc --version
    - name: build release
      run: git config --global --add safe.directory '*' && make release
