---
name: Release simulation

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  centos_7:
    name: centos_7
    runs-on: ubuntu-24.04
    container:
      image: centos:7
      volumes:
        - /node20217:/node20217:rw,rshared
        - /node20217:/__e/node20:ro,rshared
    steps:
    - name: fix packages
      run: sed -i -e '/^mirrorlist/d;/^#baseurl=/{s,^#,,;s,/mirror,/vault,;}' /etc/yum.repos.d/CentOS*.repo && yum update -y
    - name: install git
      run: yum update -y && yum -y install https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm && yum install -y git
    - name: nodejs
      run: |
        yum install -y wget xz
        wget https://unofficial-builds.nodejs.org/download/release/v20.9.0/node-v20.9.0-linux-x64-glibc-217.tar.xz
        tar -xf node-v20.9.0-linux-x64-glibc-217.tar.xz --strip-components 1 -C /node20217
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install packages
      run: yum update -y && yum install -y install libcurl-devel zlib-devel gcc make wget
    - name: env
      run: ldd --version && gcc --version
    - name: build release
      run: git config --global --add safe.directory '*' && make release
