---
name: Release simulation

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  centos_7:
    name: centos_7
    runs-on: ubuntu-20.04
    container: centos:7
    steps:
    # - name: install git
    #   run: sudo apt-get install -y software-properties-common && sudo add-apt-repository -y ppa:git-core/ppa && sudo apt-get update -y && sudo apt-get install git -y
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install packages
      run: sudo yum update && sudo yum install -y install libcurl-devel zlib-devel
    - name: env
      run: lsb_release -a &&  ldd --version && gcc --version && g++ --version
    - name: build release
      run: make release
